name: issues
on:
  issues:
    types: [opened]
jobs:
  issues-example:
    runs-on: ubuntu-latest
    steps:
      - name: log titel
        run: |
          echo Issue Title
          echo ${{github.event.issue.title}}

      - name: log body
        run: echo ${{ github.event.issue.body }}

  
