name: Steps Example
on:
  workflow_dispatch:

jobs:
  steps-example:
    runs-on: ubuntu-latest
    steps:
      - name: Make directory
        run: mkdir testmachine

      - name: execute uname command
        run: uname -a > testmachine/output.txt

      - name: Check content of txt file
        run: cat testmachine/output.txt

      - name: Check directory output
        run: ls -alhR
  
